FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.25-openshift-4.22 AS builder
WORKDIR /go/src/github.com/openshift/crd-schema-checker
COPY . .
ENV GO_PACKAGE github.com/openshift/crd-schema-checker
RUN make build --warn-undefined-variables

FROM registry.ci.openshift.org/ocp/4.17:base-rhel9
COPY --from=builder /go/src/github.com/openshift/crd-schema-checker/crd-schema-checker /usr/bin/
