FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14 AS builder
WORKDIR /go/src/github.com/openshift/crd-schema-checker
COPY . .
ENV GO_PACKAGE github.com/openshift/crd-schema-checker
RUN make build --warn-undefined-variables

FROM registry.ci.openshift.org/ocp/4.14:base
COPY --from=builder /go/src/github.com/openshift/crd-schema-checker/crd-schema-checker /usr/bin/
